# Generated by Django 4.2.7 on 2024-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0004_bloqueo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='qr_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
