# Generated by Django 4.2.7 on 2024-09-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0005_reserva_qr_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado_qr',
            field=models.BooleanField(default=True),
        ),
    ]
