# Generated by Django 4.2.7 on 2024-09-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0006_reserva_estado_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='entradas',
            field=models.BooleanField(default=False),
        ),
    ]
