# Generated by Django 4.2.7 on 2024-09-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0007_evento_entradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='entradasQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(max_length=100, unique=True)),
                ('qr_imagen', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('estado_qr', models.BooleanField(default=True)),
                ('tipo_entrada', models.CharField(default='General', max_length=10)),
                ('compra', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Oasis.compraentrada')),
            ],
        ),
    ]
