# Generated by Django 4.2.7 on 2024-10-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0008_entradasqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
