# Generated by Django 4.2.7 on 2024-10-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0009_evento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='qr_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mesas_qr_codes/'),
        ),
    ]
