# Generated by Django 4.2.7 on 2024-10-10 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0010_mesa_qr_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='token_recuperar',
            new_name='codigo_recuperar',
        ),
    ]
