# Generated by Django 4.2.7 on 2024-10-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0011_rename_token_recuperar_usuario_codigo_recuperar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='codigo_recuperar',
            new_name='token_recuperar',
        ),
    ]
