# Generated by Django 4.2.7 on 2024-10-13 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0012_rename_codigo_recuperar_usuario_token_recuperar'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ganancia_entradas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='ganancia_reservas',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Ganancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Oasis.evento')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Oasis.mesa')),
            ],
        ),
    ]
