# Generated by Django 4.2.7 on 2024-10-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0013_evento_ganancia_entradas_evento_ganancia_reservas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ganancia_total',
            field=models.IntegerField(default=0),
        ),
    ]
