# Generated by Django 4.2.6 on 2024-10-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0014_evento_ganancia_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='total_ganancia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Ganancias',
        ),
    ]
