# Generated by Django 4.2.7 on 2024-10-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0015_pedido_fecha_creacion_delete_ganancias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_creacion',
        ),
    ]
