# Generated by Django 5.1.1 on 2024-10-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0016_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='mostrar_en_reporte',
            field=models.BooleanField(default=True),
        ),
    ]
