# Generated by Django 4.2.6 on 2024-10-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0017_pago_mostrar_en_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='ganancia_reserva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='total_pagado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
