# Generated by Django 5.1.1 on 2024-10-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oasis', '0018_mesa_ganancia_reserva_alter_pago_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='pedidos',
            field=models.IntegerField(default=0),
        ),
    ]
